meta:
  title: Ionic Presentation
  thumbnail:
  description: Personal ionic presentation
  sns:
    - twitter
slide:
  loop: false
  sidebar: true
  targetBlank: true
  showIndex: true
  isVertical: true
  code:
    languages:
      - javascript
      - shell
    plugins: []
    theme: default
  chart: false
  math: false
extends:
  js:
  css: ./style.css
